name: Build and Push Docker Image
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    branches:
      - main
      - dev
  workflow_dispatch: 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Azure Container Registry
        if: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev') }}
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      # - name: Log in to GitHub Container Registry
      #   if: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev') }}
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: Harmanpreet-Microsoft
      #     password: ${{ secrets.GH_TOKEN }}
      - name: Set Docker image tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "TAG=dev" >> $GITHUB_ENV
          else
            echo "TAG=pullrequest-ignore" >> $GITHUB_ENV
          fi
          
      - name: Build and push Docker km-charts-function image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/km-charts-function:${{ env.TAG }} -f AzureFunctions/km-charts-function/Dockerfile AzureFunctions/km-charts-function && \
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/km-charts-function:${{ env.TAG }} 
            
      - name: Build and push Docker km-rag-function image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/km-rag-function:${{ env.TAG }} -f AzureFunctions/km-rag-function/Dockerfile AzureFunctions/km-rag-function && \
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/km-rag-function:${{ env.TAG }} 
      - name: Build and push Docker km-app image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/km-app:${{ env.TAG }} -f App/WebApp.Dockerfile App && \
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/km-app:${{ env.TAG }} 
